{% set name = "oslo.utils" %}
{% set version = "9.2.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "1f42006de6b9291a0305025f5ccdb8907120d88ed7ebc3784a1472a3328048ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://files.pythonhosted.org/packages/12/fe/22b08a1234826f3baace1d46494f764625a6e6753b8e4b3809aa93ae35b3/oslo_utils-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >={{ python_min }}
    - iso8601 >=0.1.11
    - oslo.i18n >=3.15.3
    - netaddr >=0.10.0
    - debtcollector >=1.2.0
    - pyparsing >=2.1.0
    - packaging >=20.4
    - python-tzdata >=2022.4
    - PyYAML >=3.13
    - psutil >=3.2.2

test:
  imports:
    - oslo_utils
    - oslo_utils.encodeutils
    - oslo_utils.eventletutils
    - oslo_utils.excutils
    - oslo_utils.fileutils
    - oslo_utils.importutils
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://docs.openstack.org/developer/oslo.utils/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Support for common utility type functions, such as encoding, exception handling, string manipulation, and time handling.
  doc_url: https://docs.openstack.org/developer/oslo.utils/
  dev_url: https://git.openstack.org/cgit/openstack/oslo.utils

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
