{% set name = "oslo.utils" %}
{% set version = "3.42.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "f5ae91be7869dbe8db014938f835c645b17f5f96de640c5a958b829d77098f65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - six >=1.10.0
    - funcsigs >=1.0.0  # [py2k]
    - iso8601 >=0.1.11
    - oslo.i18n >=3.15.3
    - monotonic >=0.6
    - pytz >=2013.6
    - netaddr >=0.7.18
    - netifaces >=0.10.4
    - debtcollector >=1.2.0
    - pyparsing >=2.1.0

test:
  imports:
    - oslo_utils
    - oslo_utils.encodeutils
    - oslo_utils.eventletutils
    - oslo_utils.excutils
    - oslo_utils.fileutils
    - oslo_utils.fixture
    - oslo_utils.importutils

about:
  home: https://docs.openstack.org/developer/oslo.utils/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Support for common utility type functions, such as encoding, exception handling, string manipulation, and time handling.
  doc_url: https://docs.openstack.org/developer/oslo.utils/
  dev_url: https://git.openstack.org/cgit/openstack/oslo.utils

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
