appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: d9OYfgq8IzFNLikxRp4q8WKzDKNlVlmli9lxfoZqr3SFeXBoBmcaZpFSoqeka+XyZHqEU3tuaMpwGEnA+TdzR4rDs0uBIfGJm9Ps+y/8b1y4VcqI0h8zp2+TFsPhYBkL3RGSdljz6G84ls3maEhCbXYVvPb47f1R+uoU5ocxINPpj2OnXOs2Bh04is+SIjGneHg13qKYsi45iYBfSLPyRE+PmbiTctGYR09t3wCAP2u5jktfzBuMhz3ozrUAxV5q41lfQKo+QU4Klzz2qMlSy7UMPHalWGiUFw10FfAg6hYyhJbUeG5U+9IiQ15Nnok5dxJcczFB+33GrTM6FbUBrJN/o3T1lvCQeFjdnHGoflxZqZ8/EDJn2QJqrfIqOOGItkjGNMPuKWuvgUaQmdR3rU/W6NREKrgOV0tKY97ieIGfJ58wWoThAuhEIc5TdUiAbQYUMTuFov1vkzJNzG3ADH0DyBnKVlSTbrfhorsA+VGI7PT7qQshKOpDaSaLUYH/rLqLPrhubGh2JxBV9U/hz4+EwgycLfSiwooN389eV++cu25mQgRZQk1BwfrqFUs4IgFVyRQWKz8IGFNPYBrzxpHsbUHlLZU+JPnv1V7ZhmwShVjZnbNviaZluill3d+y0Ljtb24B8scg3HDNolwWAT+Mx4BSDaOLzDQN5NPrHFk=}
provider:
  win: azure
conda_forge_output_validation: true
